if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.8.1")
    message(FATAL_ERROR "GCC version must be greater than or equal to 4.8.1!")
  endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "3.3.0")
    message(FATAL_ERROR "Clang version must be greater than or equal to 3.3.0!")
  endif()
else()
  message(FATAL_ERROR "Unknown compiler in use. Only gcc and clang are currently supported!")
endif()
